### ISSUE TITLE
Client Login Issue

### ISSUE THREAD

**Issue by Isaac-Lee** [JayJay-H/British_in_December#11]
클라이언트가 로그인할때 리턴값이 스티링이라서 그사람이 로그인했는지 안했는지 판별 불가함.

이거 서버 클래스에서 수정해야할듯.

**Comment by uinone** [comment]
수정 완료

**Comment by Isaac-Lee** [comment]
클라이언트 로그인 컨트롤러 부분에서

각 로그인케이스 별로 메시지 출력하는 코드 구현

**Comment by Isaac-Lee** [comment]
해결완료
