### ISSUE TITLE
클라이언트 구현 이슈 - 사용자 위치 구현문제

### ISSUE THREAD

**Issue by Isaac-Lee** [JayJay-H/British_in_December#36]
- 이용시간
- 이용금액

위 두가지 모두 사용자의 위치에 따라서 달라지는 값들임
문제는 사용자의 위치를
###  **"어디서 저장하며 어디서 어떻게 구현하는가"** 
입니다.

**Comment by uinone** [comment]
사용자의 위치는 매번 달라지기 때문에 랜덤값으로 매번 킬때마다 부여하면 어떨까요?

**Comment by Isaac-Lee** [comment]
일단 해결방법으로, 클라이언트가 스쿠터를 빌리면 클라이언트 클래스를 생성,
클라이언트 클래스에는 현재 클라이언트의 위치정보와 이용요금, 이용시간들의 정보 저장
사용하고 있는 시간만큼, 이용시간과 이용요금 초기화
반납하면 해당 정보를 소캣을 통해 서버로 전달.

하는 방식은 어떤지?

**Comment by Isaac-Lee** [comment]
일단 클라이언트 클래스에 구현함.
문제는 이걸 초기화하는 방법이랑 서버에 보내는 방법을 모름

**Comment by uinone** [comment]
위치만 서버로 업데이트, 나머지는 프로그램 내에서 계산하는거 맞죠?

**Comment by Isaac-Lee** [comment]
맞습니다. 그렇게 하려고 하는데 조오금 어렵네요. 
클래스를 생성하고 쓰레드 돌리고 해야하는데 방법을 전혀 모르겠어서

**Comment by uinone** [comment]
구현 완료
