### ISSUE TITLE
클라이언트 구현 이슈 - 스쿠터 위치

### ISSUE THREAD

**Issue by Isaac-Lee** [JayJay-H/British_in_December#37]
사용자가 스쿠터를 반납함에 따라 스쿠터의 위치가 달라짐

이것 또한
### **"어디서 어떻게 구현할 것인가"**

**Comment by uinone** [comment]
수직선으로 구현하는 것에 대해 더 고민해봐야할듯 함.

**Comment by uinone** [comment]
구현 완료
