### ISSUE TITLE
클라이언트 구현 이슈 - 실시간으로 바뀌는 필드 구현

### ISSUE THREAD

**Issue by Isaac-Lee** [JayJay-H/British_in_December#38]
- 이용시간
- 이용금액

위 두가지는 클라이언트 GUI 상에서 실시간으로 초기화 되어야하는 부분임

### **어떻게 구현해서 초기화 시킬 것인지**

**Comment by uinone** [comment]
초시계 만들 때 썼던 timeLine 스레드를 변형시켜서 만들면 되지 않을까?

**Comment by Isaac-Lee** [comment]
확인 해보겠음

**Comment by Isaac-Lee** [comment]
수정 완료 해결됨
