### ISSUE TITLE
클라이언트 구현이슈 - 사용가능 한 스쿠터

### ISSUE THREAD

**Issue by Isaac-Lee** [JayJay-H/British_in_December#39]
현재 스쿠터가 사용가능 하던 사용가능 하지 않던 빌릴 수 있다.

### **사용가능 할 때만 빌릴 수 있게 수정**

**Comment by uinone** [comment]
수정하라는거??

**Comment by Isaac-Lee** [comment]
스쿠터가 사용가능한지 아닌지 판단 할 수 있는 무언가가 필요함.
db에서 그런 정보를 전달해 주던지...

그리고 사용가능한 수쿠터들의 정보를 저징하은 부분도 팔요...

**Comment by uinone** [comment]
일단 확인

**Comment by uinone** [comment]
구현 완료
